quarkus.datasource.db-kind=postgresql

%dev.quarkus.http.port=8089
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=123456
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/order_db
%dev.kafka.bootstrap.servers=localhost:9092



quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.migrate-at-start=true
mp.messaging.outgoing.order-events-out.connector=smallrye-kafka
mp.messaging.outgoing.order-events-out.topic=order-events
mp.messaging.outgoing.order-events-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.order-events-out.key.serializer=org.apache.kafka.common.serialization.StringSerializer

#
#mp.messaging.incoming.inventory-events-in.connector=smallrye-kafka
#mp.messaging.incoming.inventory-events-in.topic=inventory-events
#mp.messaging.incoming.inventory-events-in.group.id=order-service
#mp.messaging.incoming.inventory-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer



mp.messaging.incoming.payment-events-in.connector=smallrye-kafka
mp.messaging.incoming.payment-events-in.topic=payment-events
mp.messaging.incoming.payment-events-in.group.id=order-service-payment
mp.messaging.incoming.payment-events-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer